name: Auto Pull Request

on:
  push:
    branches:
      - public

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: pr
        run: |
          if gh pr list --state open --head public --base heroku | grep -q "No pull requests found"; then 
            echo "pr_exist=false"; 
            echo "No existing pull requests found."
          else 
            echo "pr_exist=true"; 
            echo "Existing pull requests found."
          fi
        env:
          GH_TOKEN: ${{ github.token }}
      - id: changes
        run: |
          if git diff --quiet; then
            echo "changes_exist=false";
            echo "No changes found."
          else
            echo "changes_exist=true";
            echo "Changes found."
          fi
      - name: Create Pull Request
        if: steps.pr.outputs.pr_exist == 'false' && steps.changes.outputs.changes_exist == 'true'
        run: gh pr create --title "Automatic Pull Request" --body "This pull request was automatically generated when the `public` branch was updated." --base heroku --head public
        env:
          GH_TOKEN: ${{ github.token }}
